# Welcome to NumPy world 

In [2]:
import numpy as np

In [3]:
myarr = np.array([[1000, 2000, 3000, 4000]], np.int64)

In [4]:
myarr[0,1]

2000

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int64')

In [7]:
myarr[0,1]

2000

In [8]:
myarr[0, 1] = 66

In [9]:
myarr

array([[1000,   66, 3000, 4000]])

# Array creation method

**1. Conversion from other Python structures**

In [12]:
listarray = np.array([[1, 2, 3], [5, 8, 5], [0, 3, 1]])

In [13]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [14]:
listarray.dtype

dtype('int64')

In [15]:
listarray.shape

(3, 3)

In [16]:
listarray.size

9

In [17]:
#better to use float and int in numpy for data processing

In [18]:
np.array({1, 2, 3})

array({1, 2, 3}, dtype=object)

**2. intrinsic numpy array creation objects**

In [20]:
zeros = np.zeros((2, 5))

In [21]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
zeros.dtype

dtype('float64')

In [23]:
zeros.shape

(2, 5)

In [24]:
rng = np.arange(15)

In [25]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
lspace = np.linspace(1, 5, 10)

In [27]:
lspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [28]:
emp = np.empty((4, 6))

In [29]:
emp

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [30]:
emp_like = np.empty_like((lspace))

In [31]:
emp_like

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [32]:
ide = np.identity(45)

In [33]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [34]:
ide.shape

(45, 45)

In [35]:
arr = np.arange(99)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [37]:
#on multiply it should be 99 => 3*33 not 3*31

In [38]:
arr.reshape(3, 33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [39]:
arr = arr.reshape(3,33)

In [40]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [41]:
arr.shape

(3, 33)

In [42]:
arr = arr.ravel()

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [44]:
arr.shape

(99,)

# Numpy Axis

In [46]:
ar = np.array([[1, 2, 3], [4, 5, 6], [7, 1, 0]])

In [47]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [48]:
ar.sum(axis=0)

array([12,  8,  9])

In [49]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [50]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [51]:
ar.flat

In [52]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [53]:
#no. of dimention

In [54]:
ar.ndim

2

In [55]:
ar.size

9

In [56]:
#total bytes consumed by ar

In [57]:
ar.nbytes

72

In [111]:
#no brakets are attribute and with brakets are methods

In [113]:
one = np.array([1, 3, 4, 634, 2])

In [115]:
#find min and max nos. index

In [117]:
one.argmax()

3

In [119]:
one.argmin()

0

In [121]:
one.argsort()

array([0, 4, 1, 2, 3])

In [123]:
ar.argmin()

8

In [125]:
ar.argmax()

6

In [127]:
ar.argmax(axis=0)

array([2, 1, 1])

In [129]:
ar.argmax(axis=1)

array([2, 2, 0])

In [131]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [133]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [135]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [139]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [143]:
ar.reshape((1,9))

array([[1, 2, 3, 4, 5, 6, 7, 1, 0]])

In [145]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [151]:
ar2 = np.array([[1, 2, 21],
       [4, 5, 6],
       [7, 1, 0]])

In [153]:
ar + ar2

array([[ 2,  4, 24],
       [ 8, 10, 12],
       [14,  2,  0]])

In [155]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

In [157]:
ar * ar2

array([[ 1,  4, 63],
       [16, 25, 36],
       [49,  1,  0]])

In [161]:
ar % ar2

/var/folders/cx/6fm42bl13kxc0txpzrxqkp0m0000gn/T/ipykernel_87383/3841496730.py:1: RuntimeWarning: divide by zero encountered in remainder
  ar % ar2


array([[0, 0, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [165]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [167]:
ar.sum()

29

In [169]:
ar.max()

7

In [171]:
ar.min()

0

In [173]:
#finding element in an array

In [175]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [183]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [185]:
type(np.where(ar>5))

tuple

In [187]:
np.count_nonzero(ar)

8

In [191]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [193]:
ar[1, 2] = 0

In [195]:
np.count_nonzero(ar)

7

In [199]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

In [201]:
import sys

In [203]:
py_ar = [0, 4, 55, 2]

In [205]:
np_ar = np.array(py_ar)

In [211]:
#size of python array

In [207]:
sys.getsizeof(1) * len(py_ar)

112

In [209]:
np_ar.itemsize * np_ar.size

32

In [213]:
#create numpy arrays python list

In [215]:
np_ar.tolist()

[0, 4, 55, 2]